config/routes.rb
Rails.application.routes.draw do
    
 
  root to: 'flights#index'
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
  get '/login' => 'session#new'
  post '/login' => 'session#create' 
  delete '/login' =>'session#destroy'

  get '/flights/search' =>'flights#search'

  resources :flights
  resources :airplanes
  resources :users
  resources :reservations



end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airplane
  has_many :reservations
  has_many :users, through: 'reservations'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flight
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_many :reservations
  has_many :flights, through: 'reservations'
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  def new
    @airplane = Airplane.new
  end

  def create
    Airplane.create airplane_params

    redirect_to airplanes_path
  end

  def index
    @airplanes = Airplane.all
  end

  def show
    @airplane = Airplane.find params[:id]
    @row = 1
    @column = 0
    @column_letters = ('A'..'Z').to_a
  end

  def edit
    @airplane = Airplane.find params[:id]
  end

  def update
    airplane = Airplane.find params[:id]
    airplane.update! airplane_params
    redirect_to airplane_path(params[:id])
  end

  def destroy
    Airplane.destroy params[:id]
    redirect_to airplanes_path
  end
  
  private
  
  def airplane_params
    params.require(:airplane).permit(:name, :rows, :columns)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :fetch_user

    def fetch_user 
        if session[:user_id].present?
            @current_user = User.find_by id: session[:user_id]
        end
        session[:user_id] = nil unless @current_user.present?
    end 

    def check_if_logged_in
        unless @current_user.present?
            flash[:error] = "You must be logged in!"
            redirect_to login_path
        end
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  before_action :fetch_user

  before_action :check_if_logged_in, only: [:new, :edit, :destroy, :create]

  def new
    @flight = Flight.new
  end

  def create
    Flight.create flight_params
    redirect_to flights_path
  end

  def index
    @flights = Flight.all.order('date_flight ASC')
  end

  def show
    flight = Flight.find params[:id ]
    plane = Airplane.find flight.airplane_id
    reservation = Reservation.where(flight_id: flight.id)
    current_seat = flight.reservations.count
    total_seat = flight.airplane.rows * flight.airplane.columns
    seat_cal = total_seat - current_seat
    if flight
      render json: {flight: flight, plane: plane, reservation: reservation, available_seat: seat_cal}
    else
      render json: { error: "No details found"}
    end
  end


  def edit
    @flight = Flight.find params[:id]
  end

  def update
    flight = Flight.find params[:id]
    flight.update! flight_params
    redirect_to flights_path
  end

  def destroy
    Flight.destroy params[:id]
    redirect_to flights_path
  end

  def search


    flights = Flight.where("origin ILIKE ? and destination ILIKE ?", "%#{params[:origin]}%", "%#{params[:destination]}%")
    
    if flights.any?      
      plane = []
  
      flights.each do |f|
        plane.push(f.airplane)  
      end
      
        render json: {flight: flights,plane: plane}

    else    
        render json: {error: "No flights found"}, status: 404
    end
  end

  private
  def flight_params
    params.require(:flight).permit(
      :date_flight,
      :origin,
      :destination,
      :airplane_id
    )
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :verify_authenticity_token,  raise: false

  def new
    @reservation = Reservation.new
  end

  def create
    result = Reservation.create(
      user_id: params[:user_id],
      flight_id: params[:flight_id],
      row: params[:row],
      column: params[:column]
    )
    if result.persisted?
      render json: result
    else
      render json: {error: "There was an error booking"}
    end
    
    
  end

  def index
  end

  def show
    @reservation = Reservation.find params[:id]
  end

  def edit
    @reservation = Reservation.find params[:id]

  end

  def update
  end

  def destroy
    @reservation.destroy
  end

  private

  def reservation_params
    #params.require(:reservation).permit(:row, :column, :user_id, :flight_id)
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new

    end
  
    def create
        #If we want to add the sign up function#
        user = User.find_by email: params[:email]
        if user.present? && user.authenticate(params[:password])
          if user.admin === true 
            session[:user_id] = user.id
            redirect_to root_path
          else
            redirect_to login_path
            flash[:error] = "Sorry, you don't have access."
          end
        else    
          redirect_to login_path
          flash[:error] = "Bad Credentials, try again."
        end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to login_path
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    
    @user.save
    
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to user_path(params[:id])
    else
      flash[:error] = 'Invalid email or password'
      render :new
    end
  end

  def index
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update! user_params
    redirect_to user_path(params[:id])
  end

  def destroy
    User.destroy params[:id]
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(
      :email,
      :name,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/airplanes/_form.html.erb
<div class="row">
    <div class="col-md-12">
        <%= form_with model: @airplane, local: true do |f| %>
            <%= f.label :name, :class=> "form-label" %>
            <%= f.text_field :name,:class=> "form-control" , :required => true %>
            <%= f.label :rows, :class=> "form-label" %>
            <%= f.number_field :rows,  :class=>'form-control', :required => true %>
            <%= f.label :Columns, :class=> 'form-label'  %>
            <%= f.number_field :columns,:class=> 'form-control', :required => true %>
            <%= f.submit 'Save',  :class => 'btn btn-primary col-md-2 my-3' %>
        <% end %>
    </div>
</div>
 
                            

app/views/airplanes/edit.html.erb
<div class="container p-4"> 
        <div class="row">
             <div class="col-md-12">
                <h4>Edit Airplane</h3> 
            </div>
        </div>
        <hr>
        <div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-8">
                <div class="card-header d-flex justify-content-between">
                    <div> <h4>Editing  </h4> </div>
                    <div> <%= link_to 'Go Back', airplanes_path, :class => 'btn btn-outline-primary' %></div>
                </div>
                <div class="card-body">
                    <%= render partial: 'form' %>
                </div>
                </div>
        </div>
           
</div>

app/views/airplanes/index.html.erb
<div class="container p-4"> 
        <div class="row">
             <div class="col-md-12">
                <h4>Virgin Airlines </h3> 
            </div>
        </div>
        <hr>
        <div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-8">
                <div class="card-header d-flex justify-content-between">
                    <div> <h4>All Airplanes</h4> </div>
                    <div> <%= link_to 'Create Plane', new_airplane_path, :class => 'btn btn-outline-danger' %></div>
                </div>
                <div class="card-body">
                    <table class="table  table-hover table-bordered">

                <tr class="bg-light"> 
                    <th>Plane Model</th>
                    <th>Rows</th>
                    <th>Columns</th>
                    <th> Actions </th>

            <% @airplanes.each do |a| %>
                <tr>
                    <td> <%= a.name%> </td>
                    <td> <%= a.rows %> </td>
                    <td> <%= a.columns %> </td>
                    <td><%= link_to 'Show', airplane_path(a.id) %></td>
                </tr>
            <% end %>

        </table>
                </div>
            </div>
        </div>
           
</div>

app/views/airplanes/new.html.erb
<div class="container p-4"> 
        <div class="row">
             <div class="col-md-12">
                <h4>Create Airplane</h3> 
            </div>
        </div>
        <hr>
        <div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-8">
                <div class="card-header d-flex justify-content-between">
                    <div> <h4>New </h4> </div>
                    <div> <%= link_to 'Go Back', airplanes_path, :class => 'btn btn-outline-primary' %></div>
                </div>
                <div class="card-body">
                    <%= render partial: 'form' %>
                </div>
                </div>
        </div>
           
</div>

app/views/airplanes/show.html.erb
<div class="container p-4"> 
      <div class=w">
            <div class="col-md-12">
              <h4><%= @airplane.name %> </h3> 
          </div>
      </div>
      <hr>
      <div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-12">
                <div class="card-header d-flex justify-content-between">
                    <div> <h4>Seat Map </h4> </div>
                    <div> 
                      <%= link_to 'Edit', edit_airplane_path(@airplane), :class => 'btn btn-outline-danger' %> 
                      <%= link_to 'Delete', airplane_path(@airplane),:class => 'btn btn-outline-danger', method: 'delete' %>
                      <%= link_to 'Go Back', airplanes_path, :class => 'btn btn-outline-danger' %>
                    </div>
                </div>
                <div class="card-body">
                    <div class="seat_details ">
                        <% @airplane.rows.times do %>
                        <div class="columns ">
                          <p id = "column-letters text-center"><%= @column_letters[@column] %></p>
                          <% @airplane.columns.times do %>
                            <div class="seats">
                              <%= @row %>
                              <% @row += 1 %>
                            </div>
                          <% end %>
                        </div>

                        <% @row = 1 %>
                        <% @column += 1 %>
                        <% end %>
                      </div>
                </div>
                </div>
        </div>
</div>

app/views/airplanes/update.html.erb
<h1>Airplanes#update</h1>
<p>Find me in app/views/airplanes/update.html.erb</p>

app/views/flights/_form.html.erb
<div class="row">
    <div class="col-md-12">
    <%= form_with model: @flight, local: true do |f| %>
        <%= f.label :date, :class=>'form-label' %>
        <%= f.date_field :date_flight,:class=>'form-control', required: "true"  %>
        <%= f.label :origin, :class=>'form-label' %>
        <%= f.text_field :origin,:class=>'form-control', required: "true"  %>
        <%= f.label :destination,:class=>'form-label'  %>
        <%= f.text_field :destination,:class=>'form-control', required: "true"  %>
        <%= f.label :plane, :class=>'form-label'   %>
        <%= f.collection_select :airplane_id, Airplane.all, :id, :name, { include_blank: "Select option..." }, { class: "form-select",  required: "true" } %>
        <%= f.submit  :class => 'btn btn-primary col-md-2 my-3' %>
    <% end %>
    </div>
</div>

app/views/flights/edit.html.erb
<div class="container p-4"> 
        <div class="row">
             <div class="col-md-12">
                <h4>Edit Airplane</h3> 
            </div>
        </div>
        <hr>
        <div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-8">
                <div class="card-header d-flex justify-content-between">
                    <div> <h5> Edit Flight: <%= @flight.id %> - <%= @flight.origin %> to <%= @flight.destination %> </h5></div>
                    <div> <%= link_to 'Go Back', flights_path, :class => 'btn btn-outline-primary' %></div>
                </div>
                <div class="card-body">
                    <%= render partial: 'form' %>
                    </div>
                </div>
        </div>
           
</div>

app/views/flights/index.html.erb
<div class="container p-4"> 
        <div class="row">
             <div class="col-md-12">
                <h4>All Flights </h3> 

            </div>
        </div>
        <hr>

<div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-8">
                <div class="card-header d-flex justify-content-between">
                    <div> <h4>Flights</h4> </div>
                    <% if @current_user && @current_user.admin %>
                      <div> <%= link_to 'Create Flight', new_flight_path, :class => 'btn btn-outline-danger' %></div>
                    <% end %>
                </div>
                <div class="card-body">
              <table class="table  table-hover table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Flight</th>
      <th>From > To</th>
      <th>Plane</th>
      <th>Total Seats</th>
      <th>Available Seats</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @flights.each do |f|%>
      <tr>
        <td><%= f.date_flight.strftime("%d/%m/%Y") %></td>
        <td><%= (sprintf 'BA-%02d', f.id) %></td>
        <td><%= f.origin %> > <%= f.destination %></td>
        <td><%= f.airplane.name%></td>
        <td><%= f.airplane.rows * f.airplane.columns %></td>
        <td><%= (f.airplane.rows * f.airplane.columns) - f.reservations.count %></td>
        
        <% if @current_user && @current_user.admin %>

          <td>
            <%= link_to 'Edit', edit_flight_path(f)%> 
            <%= link_to 'Delete', flight_path(f), method: 'delete' %>
          </td>
        <% end %>
    <% end%>




      </tr>
  </tbody>
</table>

           

                </div>
                </div>
        </div>



</div>

app/views/flights/new.html.erb
<div class="container p-4"> 
        <div class="row">
             <div class="col-md-12">
                <h4>Create New Flight</h3> 
            </div>
        </div>
        <hr>
        <div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-8">
                <div class="card-header d-flex justify-content-between">
                    <div> <h5> Adding new flight </h5></div>
                    <div> <%= link_to 'Go Back', flights_path, :class => 'btn btn-outline-primary' %></div>
                </div>
                <div class="card-body">
                    <%= render partial: 'form' %>
                    </div>
                </div>
        </div>
</div>

app/views/flights/show.html.erb
<div class="container p-4"> 
      <div class="row">
            <div class="col-md-12">
              <h4> Flight details </h3> 
          </div>
      </div>
      <hr>
      <div class="d-flex justify-content-center my-5"> 
            <div class="card col-md-12">
                <div class="card-header d-flex justify-content-between">
                    <div> <h4>Seat Map </h4> </div>
                    <div> 
                    
                      <%= link_to 'Go Back', flights_path, :class => 'btn btn-outline-danger' %>
                    </div>
                </div>
                <div class="card-body">
                <p> Available Seats: <%= @seat_cal %> </P>
                    <% @flight.reservations.each do |seats| %>
                        <p>Row: <%= seats.row%></p>
                        <p>Column: <%= seats.column%></p>
                    <% end %>
                    <div class="seat_details ">
                        <% @flight.airplane.rows.times do %>
                            <div class="columns ">
                            <p id = "column-letters text-center"><%= @column_letters[@column] %></p>
                            <% @flight.airplane.columns.times do %>
                                <div class="seats">
                                <%= @row %>
                                <% @row += 1 %>
                                </div>
                            <% end %>
                            </div>

                            <% @row = 1 %>
                            <% @column += 1 %>
                            <% end %>
                      </div>
                </div>
                </div>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>RailsBaBackend</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <%= stylesheet_link_tag 'application', media: 'all' %>
   </head>
   <body>
      <header class="nav-banner">
      <nav class="navbar container-fluid navbar-expand-sm navbar-light bg-danger">
         <div class="container">
            <a class="navbar-brand  text-light" href="/">Burning Airlines </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarSupportedContent">
               <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                  <% if @current_user && @current_user.admin %>
                  <li class="nav-item">
                     <%= link_to 'Airplanes', airplanes_path, :class=> 'nav-link text-light' %>
                  </li>
                  <li class="nav-item  ">
                     <%= link_to 'Flights', flights_path, :class=> 'nav-link text-light'%>
                  </li>
                  <% end %>
                  <li class="nav-item ">
                     <%= link_to 'Reservation', reservations_path, :class=> 'nav-link text-light'%>
                    
                  </li>
               </ul>
               <ul class="navbar-nav" >
                  <% if @current_user.present? %>
                  <li class="nav-item">
                     <%= link_to "#{@current_user.name}", edit_user_path(@current_user.id), :class=> 'nav-link text-light' %> 
                  </li>
                  <li class="nav-item nav-link text-light">|</li>
                  <li class="nav-item">
                     <%= link_to 'Logout', login_path, method: 'delete', :class=> 'nav-link text-light' %>
                  </li>
                  <% else %>
                  <li class="nav-item text-light">
                     <%= link_to 'Login', login_path , :class=> 'nav-link'%>
                  </li>
                  <% end %>
               </ul>
            </div>
         </div>
      </nav>
      <div class="container">
         <%= yield %>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <%= javascript_include_tag 'application' %>
   </body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<div class="container p-4"> 
        <div class="row">
             <div class="col-md-12">
                <h4>Reservations </h3> 
            </div>
        </div>
        <hr>

    <div class="d-flex justify-content-center my-5"> 
        <div class="card col-md-8">
            <div class="card-header d-flex justify-content-between">
                <div> <h4>Your Reservations</h4> </div>
                    
            </div>
                <div class="card-body">
                <table class="table  table-hover table-bordered">

                <tr class="bg-light">
                    <th>Depart date</th>
                    <th>Depart from</th>
                    <th>Arrive at</th>
                    <th>Flight</th>
                    <th>Actions</th>

                <tbody>
                <% @current_user.reservations.each do |r| %>
                    <tr>
                        <td><%= r.flight.date_flight.strftime("%d/%m/%Y") %></td>
                        <td><%= r.flight.origin %></td>
                        <td><%= r.flight.destination %></td>
                        <td><%= (sprintf 'BA-%02d', r.flight_id) %></td>
                        <td><%= link_to 'View', reservation_path(r.id) %></td>
                    </tr>
                <% end %>
                <tbody>

                </table>
                </div>
        </div>
    </div>
</div>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<div class="container p-4"> 
    <div class="row">
            <div class="col-md-12">
              <h4>Reservations </h4> 
          </div>
      </div>
      <hr>

    <div class="d-flex justify-content-center my-5"> 
        <div class="card col-md-12">
            <div class="card-header d-flex justify-content-between">
                <div> <h4>Reservation details </h4> </div>
                    <div> 
                      <%= link_to 'Edit', edit_reservation_path(@reservation), :class => 'btn btn-outline-danger' %> 
                      <%= link_to 'Delete', reservation_path(@reservation),:class => 'btn btn-outline-danger', method: 'delete' %>
                      <%= link_to 'Go Back', reservations_path, :class => 'btn btn-outline-danger' %>
                    </div>
                </div>

        <div class="card-body">

        <table class="table  table-hover table-bordered">

            <thead>
                <tr class="bg-light">
                <th>Date</th>
                <th>Depart from</th>
                <th>Destination</th>
                <th>Row</th>
                <th>Column</th>
                <th>Passenger</th>
                </tr>
            </thead>


        <tbody>

            <tr>
                <td><%= @reservation.flight.date_flight %></td>
                <td><%= @reservation.flight.origin %></td>


                <td><%= @reservation.flight.destination %></td>
                <td><%= @reservation.row %></td>
                <td><%= @reservation.column %></td>
                <td><%= @reservation.user.name %></td>
            </tr>
            

        </tbody>

        </table>
        </div>
        </div>
    </div>
</div>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/session/new.html.erb
<div class="d-flex flex-column justify-content-md-center align-items-center container-size" >
   <div class="row col-md-5">
      <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12 text-center">
                    <h2>Login</h2>
                    </div>
                </div>
                <div class="row">
                        <div class="col-md-12">
                             <% if flash[:error] %> 
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong><%= flash[:error] %> </strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                             <% end %>
                            <%= form_with url: login_path, local: true do |f| %> 
                                    <div class="col-md-12">
                                            <%= f.label :email, :class=>'form-label' %>
                                            <%= f.text_field :email, :class=> 'form-control col-md-12'%>
                                    </div>
                                    <div class="col-md-12">
                                        <%= f.label :password , :class=>'form-label' %>
                                        <%= f.password_field :password, :class=> 'form-control col-md-12'%> 
                                    </div>
                                    <div class="col-md-12 py-3">
                                        <%= f.submit "Login", :class => 'btn btn-primary col-md-12' %> 
                                    </div>
                        <% end %>
                        </div>
                </div>
            </div>
   </div>
</div>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-md-12">

        <%= form_with model: @user, local: true, html: {multipart: true} do |f| %>

            <%= f.label :email, "Email Address", :class=>'form-label' %>
            <%= f.text_field :email, :class=>'form-control', required: "true" %>

            <%= f.label :password, :class=>'form-label' %>
            <%= f.password_field :password, :class=>'form-control', required: "true" %>

            <%= f.label :password, "Confirm Password", :class=>'form-label' %>
            <%= f.password_field :password_confirmation, :class=>'form-control', required: "true" %>
        
            <%= f.label :name, :class=>'form-label' %>
            <%= f.text_field :name, :class=>'form-control', required: "true" %>


            <%= f.submit :class => 'btn btn-primary col-md-2 my-3' %>

        <% end %>

    </div>
</div>

app/views/users/edit.html.erb
<div class="container p-4"> 
    <div class="row">
        <div class="col-md-12">
            <h4>Edit User: <%= @user.name %></h4>
        </div>
    </div>
    <hr>
    <div class="d-flex justify-content-center my-5"> 
        <div class="card col-md-8">
            <div class="card-body">
                <%= render partial: 'form' %>
            </div>
        </div>
    </div> 

</div>